/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PanelProductsRouteImport } from './routes/_panel/products'
import { Route as PanelLeadsRouteImport } from './routes/_panel/leads'
import { Route as PanelDashboardRouteImport } from './routes/_panel/dashboard'
import { Route as PanelCategoriesRouteImport } from './routes/_panel/categories'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelProductsRoute = PanelProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PanelRoute,
} as any)
const PanelLeadsRoute = PanelLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDashboardRoute = PanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCategoriesRoute = PanelCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categories': typeof PanelCategoriesRoute
  '/dashboard': typeof PanelDashboardRoute
  '/leads': typeof PanelLeadsRoute
  '/products': typeof PanelProductsRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categories': typeof PanelCategoriesRoute
  '/dashboard': typeof PanelDashboardRoute
  '/leads': typeof PanelLeadsRoute
  '/products': typeof PanelProductsRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_panel': typeof PanelRouteWithChildren
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_panel/categories': typeof PanelCategoriesRoute
  '/_panel/dashboard': typeof PanelDashboardRoute
  '/_panel/leads': typeof PanelLeadsRoute
  '/_panel/products': typeof PanelProductsRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/contacts'
    | '/custom'
    | '/login'
    | '/offer'
    | '/privacy'
    | '/sitemap.xml'
    | '/categories'
    | '/dashboard'
    | '/leads'
    | '/products'
    | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/contacts'
    | '/custom'
    | '/login'
    | '/offer'
    | '/privacy'
    | '/sitemap.xml'
    | '/categories'
    | '/dashboard'
    | '/leads'
    | '/products'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/_panel'
    | '/admin'
    | '/catalog'
    | '/contacts'
    | '/custom'
    | '/login'
    | '/offer'
    | '/privacy'
    | '/sitemap.xml'
    | '/_panel/categories'
    | '/_panel/dashboard'
    | '/_panel/leads'
    | '/_panel/products'
    | '/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRouteWithChildren
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  ContactsRoute: typeof ContactsRoute
  CustomRoute: typeof CustomRoute
  LoginRoute: typeof LoginRoute
  OfferRoute: typeof OfferRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/products': {
      id: '/_panel/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PanelProductsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/leads': {
      id: '/_panel/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof PanelLeadsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/dashboard': {
      id: '/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PanelDashboardRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/categories': {
      id: '/_panel/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PanelCategoriesRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelCategoriesRoute: typeof PanelCategoriesRoute
  PanelDashboardRoute: typeof PanelDashboardRoute
  PanelLeadsRoute: typeof PanelLeadsRoute
  PanelProductsRoute: typeof PanelProductsRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelCategoriesRoute: PanelCategoriesRoute,
  PanelDashboardRoute: PanelDashboardRoute,
  PanelLeadsRoute: PanelLeadsRoute,
  PanelProductsRoute: PanelProductsRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRouteWithChildren,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  ContactsRoute: ContactsRoute,
  CustomRoute: CustomRoute,
  LoginRoute: LoginRoute,
  OfferRoute: OfferRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
